name: Trigger Doki builds

on:
  workflow_dispatch:
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true

jobs:
  build_release:
    name: Trigger Release builds 🚀
    uses: ./.github/workflows/build_release.yml

  build_legacy:
    name: Trigger Legacy builds 🚀
    uses: ./.github/workflows/build_legacy.yml
